"""Test migration - add index to rating

Revision ID: ae02e643accc
Revises: 33d3bd1f6aea
Create Date: 2026-01-11 21:59:19.853609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae02e643accc'
down_revision: Union[str, None] = '33d3bd1f6aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_movies_rating', 'movies', ['rating'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_movies_rating', table_name='movies')
    # ### end Alembic commands ###
