"""add_cast_and_crew_tables

Revision ID: f3bc8af23853
Revises: 71690e15d288
Create Date: 2026-01-11 23:13:45.449921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3bc8af23853'
down_revision: Union[str, None] = '71690e15d288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('character', sa.String(length=500), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('profile_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cast_id'), 'cast', ['id'], unique=False)
    op.create_index(op.f('ix_cast_movie_id'), 'cast', ['movie_id'], unique=False)
    op.create_index(op.f('ix_cast_name'), 'cast', ['name'], unique=False)
    op.create_index(op.f('ix_cast_person_id'), 'cast', ['person_id'], unique=False)
    op.create_table('crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('job', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('profile_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crew_department'), 'crew', ['department'], unique=False)
    op.create_index(op.f('ix_crew_id'), 'crew', ['id'], unique=False)
    op.create_index(op.f('ix_crew_movie_id'), 'crew', ['movie_id'], unique=False)
    op.create_index(op.f('ix_crew_name'), 'crew', ['name'], unique=False)
    op.create_index(op.f('ix_crew_person_id'), 'crew', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crew_person_id'), table_name='crew')
    op.drop_index(op.f('ix_crew_name'), table_name='crew')
    op.drop_index(op.f('ix_crew_movie_id'), table_name='crew')
    op.drop_index(op.f('ix_crew_id'), table_name='crew')
    op.drop_index(op.f('ix_crew_department'), table_name='crew')
    op.drop_table('crew')
    op.drop_index(op.f('ix_cast_person_id'), table_name='cast')
    op.drop_index(op.f('ix_cast_name'), table_name='cast')
    op.drop_index(op.f('ix_cast_movie_id'), table_name='cast')
    op.drop_index(op.f('ix_cast_id'), table_name='cast')
    op.drop_table('cast')
    # ### end Alembic commands ###
